database:
  user: hanko
  password: hanko
  host: localhost
  port: 5432
  dialect: postgres
smtp:
    host: smtp.example.com
    user: example
    password: example
passcode:
  email:
    from_address: no-reply@hanko.io
secrets:
  keys:
    - abcedfghijklmnopqrstuvwxyz
service:
  name: Hanko Authentication Service
