database:
  user: hanko
  password: hanko
  host: localhost
  port: 5432
  dialect: postgres
passcode:
  email:
    from_address: no-reply@hanko.io
  smtp:
    host: smtp.example.com
    user: example
    password: example
secrets:
  keys:
    - abcedfghijklmnopqrstuvwxyz
service:
  name: Hanko Authentication Service
security_notifications:
  notifications:
    password_update:
      enabled: false
    primary_email_update:
      enabled: false
    email_create:
      enabled: false
    passkey_create:
      enabled: false
  from_email:
    from_address: security@hanko.io
    from_name: Hanko Account Security
  notify_address: helpdesk@hanko.io
