name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Build
      working-directory: ./backend
      run: |
        go generate ./...
        go build -v ./...

    - name: Start test Mailslurper container
      working-directory: .
      run: docker-compose -f ./backend/test/docker-compose.test.yaml up --build -d

    - name: Test
      working-directory: ./backend
      run: go test -v ./...

    - name: Stop containers
      if: always()
      working-directory: .
      run: docker-compose -f ./backend/test/docker-compose.test.yaml down
